### ISSUE TITLE
Does not change days in a month properly, when moth changes

### ISSUE THREAD

**Issue by angel1st** [wuzhendev/flutter-cupertino-date-picker#17]
Here are the steps performed over the example app:
1. Open the calendar
1. Change language to `en`
1. Select Feb 29, 2020
1. Change Feb to Mar ==> number of days for March stays 29. although it is 31. 

If I scroll days down a bit the correct numbers appear but initially they are absent.

**Comment by wuzhendev** [comment]
please use v0.7.0
