### ISSUE TITLE
Import don't work

### ISSUE THREAD

**Issue by luizjacomn** [wuzhendev/flutter-cupertino-date-picker#21]
When I add the import statement `import 'packages:flutter_cupertino_date_picker/flutter_cupertino_date_picker.dart';` an compilatio error appears:

> Target of URI doesn't exist: 'packages:flutter_cupertino_date_picker/flutter_cupertino_date_picker.dart'.

**Comment by wuzhendev** [comment]
I created a new project, didn't appear this error. Please check your code.

1. Add the dependencies in pubspec.yaml file: 
```
dependencies:
  flutter_cupertino_date_picker: ^1.0.0+1
```
2. Execute the cmd: 
```
flutter packages get
```

**Comment by luizjacomn** [comment]
It's working! Thanks man.
