### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.

### ISSUE THREAD

**Issue by jeancarlos2020** [wuzhendev/flutter-cupertino-date-picker#40]
![image](https://user-images.githubusercontent.com/6289980/62419337-6ed49380-b643-11e9-8740-2f3dd06a6de6.png)

**Comment by jeancarlos2020** [comment]
veo incomodo tener que llamar a todos los métodos esa fue la solución 


   onClose: () => print("----- onClose -----"),
      onCancel: () => print('onCancel'),
      onChange: (dateTime, List<int> index) {
        setState(() {
          _dateTime = dateTime;
        });
      },
      onConfirm: (dateTime, List<int> index) {
        setState(() {
          _dateTime = dateTime;
        });
      }

**Comment by wuzhendev** [comment]
Please upgrade to version: v1.0.12, had fixed this bug
