### ISSUE TITLE
可以标题跟取消和确定按钮同时存在吗？

### ISSUE THREAD

**Issue by MdcGIt** [wuzhendev/flutter-cupertino-date-picker#41]
可以标题跟取消和确定按钮同时存在吗？

**Comment by wuzhendev** [comment]
自定义标题时会替代默认的标题，可以自己实现取消和确定按钮

**Comment by wuzhendev** [comment]
> 可以标题跟取消和确定按钮同时存在吗？

自定义标题时会替代默认的标题，可以自己实现取消和确定按钮

**Comment by MdcGIt** [comment]
怎么实现取消和确定按钮呢 是重写修改你的theme吗

**Comment by wuzhendev** [comment]
const DateTimePickerTheme({
  this.title,
});

通过title设置自定义的标题组件，可以参考example中的示例

**Comment by MdcGIt** [comment]
好的 非常感谢 我去试试

**Comment by MdcGIt** [comment]
确实可以了 不过在我自己定义的方法内 怎么关闭选择器和确认当前选择器的时间呢

**Comment by MdcGIt** [comment]
我怎样在自己定义的确定按钮的方法内获取当前选择器的时间呢

**Comment by wuzhendev** [comment]
目前只能通过 `onChange` 获取到当前选择器的时间
