### ISSUE TITLE
Have picker behave like Keyboard

### ISSUE THREAD

**Issue by chellyx** [wuzhendev/flutter-cupertino-date-picker#44]
i.e.: 

- Make it possible to keep the picker displayed despite page clicks

- Let the Picker displace the Page content so as to not hide fields which are under it (like the keyboard). To keep the field in focus when the Picker is opened.

There may be an easy way to do that, I'm still fairly new to Flutter and trying to get my hangs around it.

**Comment by wuzhendev** [comment]
Try to use `DatePickerWidget`. Display a date picker widget in `Stack` content, make the appearance of date picker widget like the keyboard
