### ISSUE TITLE
Confirm Button for locale='en'

### ISSUE THREAD

**Issue by mabinici** [wuzhendev/flutter-cupertino-date-picker#6]
When locale is switched to 'us', there is no Confirm/Done button.

**Comment by wuzhendev** [comment]
Please use `flutter_cupertino_date_picker: ^0.1.0`

**Comment by wuzhendev** [comment]
> When locale is switched to 'us', there is no Confirm/Done button.

Please use `flutter_cupertino_date_picker: ^0.1.0`
