### ISSUE TITLE
How to support "yyyy-MM-dd HH: mm"

### ISSUE THREAD

**Issue by fg2q1q3q** [wuzhendev/flutter-cupertino-date-picker#9]
Hello, thank you for your codes. What should I do if I want to support "yyyy-MM-dd HH: mm"

**Comment by wuzhendev** [comment]
> Hello, thank you for your codes. What should I do if I want to support "yyyy-MM-dd HH: mm"

根据格式化的参数判断要显示的时间单位，现在只支持选择年、月、日，"yyyy-MM-dd HH: mm"这种格式在年月日之后添加两栏时、分的选择器
